### ISSUE TITLE
Roadmap for Version 2.0.0

### ISSUE THREAD

**Issue by jakerella** [jakerella/jquery-mockjax#199]
This issue (and comment thread) will serve as our roadmap for version 2.0.0 of jQuery Mockjax. We'll list topics we want to address and reference issues or PRs as appropriate. The list items that get checked off have been addressed, but note that we will not necessarily be 100% done just because all items are checked off. In other words, the list can change, so stay tuned! If you have anything that you'd _like_ to be in version 2 please add it in the comments (bu tno guarantees). Also note that there will most likely be many bug fixes that we'll integrate with 2.0 (and possibly back port to 1.x).

> _A quick note on the move to version 2.0.0 versus just incrementing 1.x:_ Typically the major version update indicates potentially breaking changes and possibly a lack of backward compatability. While we are making a number of changes to the external API, we don't expect most developers to have any issues with migrating to 2.0 (at least, that's our goal). However, with the changes we're targeting right now, there is a small chance, mostly if you're using the `$.mockjaxClear()` method, using the return value from `$.mockjax()` (although we hope to minimize this), or are directly referring to the raw github file remotely. The last one is because we are moving the file from the root directory, so that remote URL will no longer work!

- [x] Module wrapper for use in such systems (started in #103, needs reworking)
- [x] Automated test running (#152)
- [x] Allow matching of request headers (#193)
- [x] Remove deprectated `$.mockjaxClear()` (we can use `$.mockjax.clear()`, see #175)
- [x] Better automation for testing against all supported jQuery versions (#176)
- [x] Remove support for jQuery <1.5.x
- [x] Fix all issues tagged with the "2.0" milestone
- [x] Add static code analysis badge to README (see #192)

**How will the changes be done?**  
Good question! Right now we have `v2` and `v1.x` branches. The intent is to maintain the 1.x branch for any hotfixes necessary, along with tagged releases. The `v2` branch will eventually become `master` and be the primary work/merge location. Note that only absolutely critical fixes will go into the `1.x` branch, but if you really need to use that, it will stick around.

Please let us know if you have any questions at all, or if you want to help!

**Comment by jakerella** [comment]
Everything is in... just need to test and get this out the door!

**Comment by jakerella** [comment]
2.0.0-beta is out the door. Thanks all!
